-- ========================================================
-- SCRIPT KHỞI TẠO BẢNG DỮ LIỆU DÀNH CHO SUPABASE
-- NomadNest - Đà Nẵng Craft Village & Workation App
-- Chạy script này tại: Supabase Dashboard -> SQL Editor
-- ========================================================

-- 1. Bảng Profiles (Thông tin người dùng / Host / Admin)
CREATE TABLE IF NOT EXISTS public.profiles (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT,
  avatar TEXT,
  role TEXT DEFAULT 'nomad_user',
  badge TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Bảng Chat Messages (Tin nhắn trao đổi)
CREATE TABLE IF NOT EXISTS public.chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_role TEXT NOT NULL,
  sender_name TEXT,
  text TEXT NOT NULL,
  timestamp TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Bảng Bookings (Đơn đặt phòng / Trải nghiệm)
CREATE TABLE IF NOT EXISTS public.bookings (
  id TEXT PRIMARY KEY,
  property_id TEXT,
  property_title TEXT,
  check_in TEXT,
  check_out TEXT,
  total_price NUMERIC,
  status TEXT DEFAULT 'confirmed',
  guest_name TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Bảng Villages (Danh sách các Làng nghề)
CREATE TABLE IF NOT EXISTS public.villages (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT,
  tags TEXT[],
  slogan TEXT,
  description TEXT,
  image TEXT,
  location TEXT,
  distance_from_center TEXT,
  highlights TEXT[],
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Bảng Properties (Cơ sở lưu trú & Phòng làm việc)
CREATE TABLE IF NOT EXISTS public.properties (
  id TEXT PRIMARY KEY,
  village_id TEXT REFERENCES public.villages(id) ON DELETE SET NULL,
  village_name TEXT,
  title TEXT NOT NULL,
  host_name TEXT,
  host_avatar TEXT,
  host_experience TEXT,
  host_bio TEXT,
  price_per_night NUMERIC,
  rating NUMERIC DEFAULT 5.0,
  reviews_count INT DEFAULT 0,
  location TEXT,
  images TEXT[],
  tags TEXT[],
  description TEXT,
  wifi_speed_mbps INT DEFAULT 100,
  workspace_type TEXT,
  max_guests INT DEFAULT 2,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Bảng Test Ping (Bảng kiểm tra kết nối hệ thống)
CREATE TABLE IF NOT EXISTS public.test_ping (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status TEXT DEFAULT 'ok',
  checked_at TIMESTAMPTZ DEFAULT NOW()
);

-- Chèn dữ liệu thử nghiệm cho test_ping
INSERT INTO public.test_ping (status) VALUES ('ok') ON CONFLICT DO NOTHING;

-- ========================================================
-- PHÂN QUYỀN TRUY CẬP (ENABLE RLS & ALLOW PUBLIC ACCESS)
-- Cho phép khóa Publishable/Anon Key đọc & ghi dữ liệu
-- ========================================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.villages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.test_ping ENABLE ROW LEVEL SECURITY;

-- Tạo chính sách (Policies) cho phép truy cập công khai Read/Write
CREATE POLICY "Public full access profiles" ON public.profiles FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public full access chat_messages" ON public.chat_messages FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public full access bookings" ON public.bookings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public full access villages" ON public.villages FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public full access properties" ON public.properties FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public full access test_ping" ON public.test_ping FOR ALL USING (true) WITH CHECK (true);

-- ========================================================
-- PHẦN BỔ SUNG: KHỞI TẠO STORAGE BUCKET "room-images"
-- Lưu trữ hình ảnh phòng & cơ sở lưu trú
-- ========================================================

-- 1. Tạo Storage Bucket "room-images" (Chế độ Public)
INSERT INTO storage.buckets (id, name, public)
VALUES ('room-images', 'room-images', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- 2. Cấp quyền Đọc (SELECT) ảnh công khai
CREATE POLICY "Public Read Access for room-images"
ON storage.objects FOR SELECT
USING (bucket_id = 'room-images');

-- 3. Cấp quyền Tải ảnh lên (INSERT) công khai
CREATE POLICY "Public Upload Access for room-images"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'room-images');

-- 4. Cấp quyền Cập nhật & Xóa (UPDATE, DELETE) ảnh
CREATE POLICY "Public Update Access for room-images"
ON storage.objects FOR UPDATE
USING (bucket_id = 'room-images');

CREATE POLICY "Public Delete Access for room-images"
ON storage.objects FOR DELETE
USING (bucket_id = 'room-images');

